name: Notify Mattermost on Ready PR

on:
  pull_request:
    types: [ready_for_review]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Send Alert to Mattermost
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
          MATTERMOST_ICON_URL: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          TEXT: |
            :dart: **Ready for Review**
            
            **Repository:** ${{ github.repository }}
            **PR:** #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}
            **Author:** ${{ github.actor }}
            
            [Review Now](${{ github.event.pull_request.html_url }})