name: Notify Mattermost on Review Requested

on:
  pull_request:
    types: [review_requested]

jobs:
  notify-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Send Alert to Mattermost
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
          MATTERMOST_ICON_URL: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          TEXT: |
            :eyes: **Review Requested**
            
            **Repo:** ${{ github.repository }}
            **PR:** #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}
            **Requested By:** ${{ github.actor }}
            **Reviewer:** @${{ github.event.requested_reviewer.login }}
            
            [Review Now](${{ github.event.pull_request.html_url }})