name: Notify Mattermost on Review Decision

on:
  pull_request_review:
    types: [submitted]

jobs:
  notify-author:
    runs-on: ubuntu-latest
    steps:
      - name: Send Alert to Mattermost
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
          MATTERMOST_ICON_URL: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          TEXT: |
            :eyes: **Review Submitted**
            
            **Repo:** ${{ github.repository }}
            **PR:** #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}
            **Reviewer:** ${{ github.actor }}
            **Verdict:** ${{ github.event.review.state }}
            
            [Read Review](${{ github.event.review.html_url }})